name: systemd_status_client
description: Monitor the server status of a systemd based server.
homepage: https://github.com/Skycoder42/systemd_status
version: 0.1.7
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  ansicolor: ^2.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^10.0.0
  freezed_annotation: ^2.4.1
  go_router: ^14.1.3
  json_annotation: ^4.9.0
  logging: ^1.2.0
  riverpod_annotation: ^2.3.5
  sentry: ^8.2.0
  sentry_dio: ^8.2.0
  sentry_flutter: ^8.2.0
  sentry_logging: ^8.2.0
  systemd_status_server:
    path: ../server
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.10.2+1
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  msix: ^3.16.7
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  sentry_dart_plugin: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#f6f5f4"
  color_dark: "#211F23"
  image: assets/splash/splash-light.png
  image_dark: assets/splash/splash-dark.png

msix_config:
  publisher: CN=E6ED0CED-8505-45BA-AA8A-1C0D6BCB2B76
  publisher_display_name: Skycoder42
  identity_name: Skycoder42.SystemdStatus
  display_name: Systemd Status
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  languages: en-us
  execution_alias: systemd_status_client
  output_path: build/windows/msix
  output_name: Systemd Status
  build_windows: false

cask:
  downloadUrl: https://github.com/Skycoder42/systemd_status/releases/download/client%2Fv#{version}/Systemd.Status.dmg

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/client%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/client%2Fv%from%...v%to%

scripts:
  gen:
    splash: dart run flutter_native_splash:create
  start:
    linux: flutter run -d linux
    web: flutter run -d web-server --web-port 8088 --dart-define=SERVER_URL=http://localhost:8080
