name: systemd_status_client
description: Monitor the server status of a systemd based server.
homepage: https://github.com/Skycoder42/systemd_status
version: 0.3.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"
resolution: workspace

platforms:
  android:
  linux:
  macos:
  windows:
  web:

dependencies:
  ansicolor: ^2.0.3
  dio: ^5.7.0
  file_picker: ^8.1.7
  firebase_auth_rest: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  http: ^1.3.0
  infinite_scroll_pagination: ^4.1.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  sentry: ^8.12.0
  sentry_dio: ^8.12.0
  sentry_flutter: ^8.12.0
  sentry_logging: ^8.12.0
  systemd_status_server:
    path: ../server
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.6.10
  dart_pre_commit: ^5.4.2
  dart_test_tools: ^6.0.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.3
  json_serializable: ^6.9.0
  msix: ^3.16.8
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  sentry_dart_plugin: ^2.3.0

flutter:
  uses-material-design: true
  generate: false # true
  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#f6f5f4"
  color_dark: "#211F23"
  image: assets/splash/splash-light.png
  image_dark: assets/splash/splash-dark.png

msix_config:
  publisher: CN=E6ED0CED-8505-45BA-AA8A-1C0D6BCB2B76
  publisher_display_name: Skycoder42
  identity_name: Skycoder42.SystemdStatus
  msstore_appId: 9ND8GH0W45WT
  display_name: Systemd Status
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  languages: en-us
  execution_alias: systemd_status_client
  output_path: build/windows/msix
  output_name: Systemd Status
  build_windows: false

cask:
  downloadUrl: https://github.com/Skycoder42/systemd_status/releases/download/client%2Fv#{version}/Systemd.Status.dmg

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/client%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/client%2Fv%from%...v%to%

scripts:
  gen:
    splash: dart run flutter_native_splash:create
  start:
    linux: flutter run -d linux
    web: flutter run -d web-server --web-port 8088 --dart-define=SERVER_URL=http://localhost:8080
