version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
