name: systemd_status_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_rpc_2: ^3.0.2
  serverpod_client: 1.2.5
  serverpod_json_rpc_2_client: ^1.0.1
  stream_channel: ^2.1.2
  systemd_status_rpc:
    path: ../systemd_status_rpc
