name: systemd_status_rpc
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_rpc_codegen: ^1.1.0
  serverpod_serialization: 1.2.6

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.8.0
  freezed: ^2.4.7
  json_rpc_codegen_builder: ^1.0.0
  json_serializable: ^6.7.1
