name: systemd_status

packages:
  - server
  - client

scripts:
  get:
    steps:
      - get:dart
      - get:flutter

  get:dart:
    packageFilters:
      flutter: false
    exec: dart pub get

  get:flutter:
    packageFilters:
      flutter: true
    exec: flutter pub get

  upgrade:
    steps:
      - upgrade:dart
      - upgrade:flutter

  upgrade:dart:
    packageFilters:
      flutter: false
    exec: >-
      dart pub add 'dev:flutter_localizations:{"sdk":"flutter"}' &&
      dart pub upgrade --major-versions --tighten &&
      dart pub remove flutter &&
      dart pub upgrade

  upgrade:flutter:
    packageFilters:
      flutter: true
    exec: flutter pub upgrade --major-versions --tighten

  build:
    run: dart run build_runner build
    exec:
      orderDependents: true

  pre-commit:init: >-
    bash -c "echo -e
    '#!/bin/sh\nexec dart pub global run melos run pre-commit:run'
    > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"

  pre-commit:remove: rm -f .git/hooks/pre-commit

  pre-commit:run:
    exec: dart run dart_pre_commit
