name: systemd_status_server
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

executables:
  systemd-status-server: main

dependencies:
  checked_yaml: ^2.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.12.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  serverpod: 1.2.5
  serverpod_json_rpc_2_server: ^1.0.0
  serverpod_shared: 1.2.5
  stream_channel: ^2.1.2
  systemd_status_rpc:
    path: ../systemd_status_rpc

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

dart_pre_commit:
  flutter-compat: false
