name: systemd_status_server
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.4.0

platforms:
  linux:

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  posix: ^6.0.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shelf: ^1.4.0
  shelf_api: ^1.0.2
  shelf_router: ^1.1.0

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.10.1
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  shelf_api_builder: ^1.0.0+1

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/server%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/server%2Fv%from%...v%to%
