name: systemd_status_server
description: Monitor the server status of a systemd based server.
homepage: https://github.com/Skycoder42/systemd_status
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.4.0

platforms:
  linux:

executables:
  systemd-status-server: server

dependencies:
  args: ^2.5.0
  build_cli_annotations: ^2.1.0
  checked_yaml: ^2.0.3
  content_length_validator: ^1.2.1
  dio: ^5.4.3+1
  firebase_verify_id_tokens: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  posix: ^6.0.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shelf: ^1.4.1
  shelf_api: ^1.2.0
  shelf_cors_headers: ^0.1.5
  shelf_helmet: ^2.3.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.11.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  shelf_api_builder: ^1.1.0

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  pkgname: systemd-status-server
  license: BSD
  depends:
    - systemd
  tagPrefix: server/v
  binariesArchivePrefix: systemd-status-server
  sourcesDir: systemd_status-server-v$pkgver/server
  extraSources:
    - name: Systemd.Status.Web-0.2.2.tar.xz
      url: https://github.com/Skycoder42/systemd_status/releases/download/client%2Fv0.2.2/Systemd.Status.Web.tar.xz
  files:
    - source: tool/package-config.yaml
      target: /etc/systemd-status-server.yaml
    - source: ../../web
      target: /usr/share/$pkgname/web-app
      recursive: true
  backup:
    - etc/systemd-status-server.yaml

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/server%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/server%2Fv%from%...v%to%
