name: systemd_status_flutter
version: 0.1.3
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  riverpod_annotation: ^2.3.5
  serverpod_auth_email_flutter: 1.2.6
  serverpod_auth_google_flutter: 1.2.6
  serverpod_auth_shared_flutter: 1.2.6
  serverpod_flutter: 1.2.6
  shared_preferences: ^2.2.3
  systemd_status_client:
    path: ../systemd_status_client
  systemd_status_rpc:
    path: ../systemd_status_rpc

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.8.1
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.5.1
  json_serializable: ^6.7.1
  msix: ^3.16.7
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#f6f5f4"
  color_dark: "#211F23"
  image: assets/splash/splash-light.png
  image_dark: assets/splash/splash-dark.png

msix_config:
  display_name: Systemd Status
  publisher: CN=de.skycoder42.systemdStatusFlutter, O=Skycoder42, C=DE
  publisher_display_name: Skycoder42
  identity_name: de.skycoder42.systemdStatusFlutter
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  languages: en-us
  execution_alias: systemd_status_flutter
  output_path: build/windows/msix
  output_name: de.skycoder42.systemdStatusFlutter
  build_windows: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/app%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/app%2Fv%from%...v%to%

scripts:
  gen:
    splash: dart run flutter_native_splash:create
  start:
    linux: flutter run -d linux
    web: flutter run -d web-server --web-port 8088
