name: systemd_status_flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 1.2.5
  systemd_status_client:
    path: ../systemd_status_client

dev_dependencies:
  custom_lint: ^0.6.2
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.6.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
