name: systemd_status_bridge
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  logging: ^1.2.0
  meta: ^1.12.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  systemd_status_client:
    path: ../systemd_status_client

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

dart_pre_commit:
  flutter-compat: false
