name: systemd_status_bridge
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  logging: ^1.2.0
  systemd_status_client:
    path: ../systemd_status_client

dev_dependencies:
  custom_lint: ^0.6.2
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.6.2
