name: systemd_status_bridge
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/Skycoder42/systemd_status
publish_to: none

environment:
  sdk: ^3.3.0

platforms:
  linux:

executables:
  systemd-status-systemctl-bridge: main

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  json_rpc_2: ^3.0.2
  logging: ^1.2.0
  meta: ^1.12.0
  posix: ^6.0.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  systemd_status_client:
    path: ../systemd_status_client
  systemd_status_rpc:
    path: ../systemd_status_rpc

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  license: BSD
  tagPrefix: bridge/v
  binariesArchivePrefix: systemd-status-systemctl-bridge

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/systemd_status/releases/tag/bridge%2Fv%tag%
    diff: https://github.com/Skycoder42/systemd_status/compare/bridge%2Fv%from%...v%to%
