allowedOrigins: []
unitFilters: []
app:
  appDir: /opt/systemd_status_server/share/web-app
  sentryDsn: null
firebase:
  projectId: PLACEHOLDER
  apiKey: PLACEHOLDER
  users: []
tls:
  pfxPath: PLACEHOLDER
  pfxPassphrase: null
