name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  packages:
    name: Packages
    uses: ./.github/workflows/packages_ci.yaml
    secrets: inherit

  apps:
    name: Apps
    needs:
      - packages
    uses: ./.github/workflows/apps_ci.yaml
    permissions:
      contents: write
    secrets: inherit
