name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  packages:
    name: systemd_status_rpc
    uses: ./.github/workflows/packages_ci.yaml

  flutter:
    name: systemd_status_flutter
    needs:
      - packages
    uses: ./.github/workflows/flutter_ci.yaml

  server_ci:
    name: systemd_status_server
    needs:
      - packages
    uses: ./.github/workflows/server_ci.yaml

  server_cd:
    name: systemd_status_server
    needs:
      - server_ci
      - flutter
    uses: ./.github/workflows/server_cd.yaml
    with:
      releaseCreated: ${{ needs.server_ci.outputs.releaseCreated }}
      releaseVersion: ${{ needs.server_ci.outputs.releaseVersion }}
      appVersion: ${{ needs.flutter.outputs.releaseVersion }}
