name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  flutter_ci:
    name: Flutter - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: systemd_status_flutter
      buildRunner: true
      unitTestPaths: ""

  flutter_build_linux:
    name: Flutter - Build flatpak bundles
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-linux.yml@main
    with:
      workingDirectory: systemd_status_flutter
      manifestPath: linux/flatpak/de.skycoder42.systemdStatusFlutter.yaml
      bundleName: de.skycoder42.systemdStatusFlutter.flatpak
    secrets:
      gpgKeyId: ${{ secrets.GPG_KEY_ID }}
      gpgKey: ${{ secrets.GPG_KEY }}

  flutter_build_windows:
    name: Flutter - Build msix installer
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-windows.yml@main
    with:
      workingDirectory: systemd_status_flutter
      buildRunner: true

  flutter_build_macos:
    name: Flutter - Build DMG image
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-macos.yml@main
    with:
      workingDirectory: systemd_status_flutter
      buildRunner: true
      dmgConfigPath: macos/dmg-config.json

  flutter_build_web:
    name: Flutter - Build web archive
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-web.yml@main
    with:
      workingDirectory: systemd_status_flutter
      buildRunner: true

  flutter_deploy:
    name: Flutter - Deploy
    uses: Skycoder42/dart_test_tools/.github/workflows/deploy.yml@main
    needs:
      - flutter_ci
      - flutter_build_linux
      - flutter_build_windows
      - flutter_build_macos
      - flutter_build_web
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.flutter_ci.outputs.enabledPlatforms }}
      workingDirectory: systemd_status_flutter
      tagPrefix: app/v
      targetRepo: Skycoder42/homebrew-systemd_status
    secrets:
      gpgKeyId: ${{ secrets.GPG_KEY_ID }}
      gpgKey: ${{ secrets.GPG_KEY }}
      targetRepoToken: ${{ secrets.HOMEBREW_REPO_PAT }}

  server_ci:
    name: Server - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: systemd_status_server
      buildRunner: true
      unitTestPaths: ""

  server_cd:
    name: Server - Compile and Release
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    needs:
      - server_ci
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.server_ci.outputs.enabledPlatforms }}
      workingDirectory: systemd_status_server
      buildRunner: true
      archivePrefix: systemd-status-server
      tagPrefix: server/v

  server_deploy:
    name: Server - Deploy
    uses: Skycoder42/dart_test_tools/.github/workflows/docker.yml@main
    needs:
      - server_cd
      - flutter_deploy
    if: needs.server_cd.outputs.releaseCreated == 'true'
    with:
      imageName: skycoder42/systemd-status-server
      version: ${{ needs.server_cd.outputs.releaseVersion }}
      dockerPlatforms: linux/amd64,linux/arm64
      dockerBuildArgs: |
        APP_VERSION=${{ needs.flutter_deploy.outputs.releaseVersion }}
    secrets:
      dockerHubUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKER_TOKEN }}
