name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  SDK_VERSION: "23.08"
  FLUTTER_SDK_GPG_KEY: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEZhVSPhYJKwYBBAHaRw8BAQdAyUCjyTVvL0R5RQZw6NeF1mcjTyxjz56RjWRE
    x+qI6dC0dFNreWNvZGVyNDIgKEdQRyBLZXkgZm9yIG9yZy5mcmVlZGVza3RvcC5T
    ZGsuRXh0ZW5zaW9uLmZsdXR0ZXIgZmxhdHBhayBidW5kbGVzKSA8U2t5Y29kZXI0
    MkB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20+iJMEExYKADsWIQRM3jbjqquCG4iR
    YqdbEIdDIpRYLgUCZhVSPgIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAK
    CRBbEIdDIpRYLmBgAP40jr4173kOMnhnIsLwgwOIunXht/KZkVRGWjHUV7wP5wD8
    C2ebyeiaya6PrQ/u+AG/mIbTPm2qgl58ESWpQXVmawC4OARmFVI+EgorBgEEAZdV
    AQUBAQdARVAUlIBUyukjFlGYscv8T49PdW4PAexZRqE1JnyMr1cDAQgHiHgEGBYK
    ACAWIQRM3jbjqquCG4iRYqdbEIdDIpRYLgUCZhVSPgIbDAAKCRBbEIdDIpRYLv5A
    AQD1vBoAhv6iM+ePgHGAnl01VyKuJfcRcsOQ7bQl5j/bKAEAzXtbKs3/rLkKlBF5
    08PRzDxSMStKeNf+L6NVrSKNVgc=
    =Cnso
    -----END PGP PUBLIC KEY BLOCK-----


jobs:
  rpc_ci:
    name: systemd_status_rpc - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: systemd_status_rpc
      buildRunner: true
      unitTestPaths: ""
  rpc_package:
    name: systemd_status_rpc - Package
    uses: Skycoder42/dart_test_tools/.github/workflows/package.yml@main
    needs:
      - rpc_ci
    with:
      workingDirectory: systemd_status_rpc
      buildRunner: true

  client_ci:
    name: systemd_status_client - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    needs:
      - rpc_package
    with:
      workingDirectory: systemd_status_client
      artifactDependencies: systemd_status_rpc
      unitTestPaths: ""
  client_package:
    name: systemd_status_client - Package
    uses: Skycoder42/dart_test_tools/.github/workflows/package.yml@main
    needs:
      - rpc_package
      - client_ci
    with:
      workingDirectory: systemd_status_client
      artifactDependencies: systemd_status_rpc

  server_ci:
    name: systemd_status_server - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    needs:
      - rpc_package
    with:
      workingDirectory: systemd_status_server
      artifactDependencies: systemd_status_rpc
      buildRunner: true
      unitTestPaths: ""
  server_cd:
    name: systemd_status_server - CD
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    needs:
      - rpc_package
      - server_ci
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.server_ci.outputs.enabledPlatforms }}
      workingDirectory: systemd_status_server
      artifactDependencies: systemd_status_rpc
      buildRunner: true
      archivePrefix: systemd-status-server
      tagPrefix: server/v
      releaseRef: refs/heads/server_pod
  server_deploy:
    name: systemd_status_server - Publish docker image
    uses: Skycoder42/dart_test_tools/.github/workflows/docker.yml@main
    needs:
      - server_cd
    if: needs.server_cd.outputs.releaseCreated == 'true'
    with:
      imageName: skycoder42/systemd-status-server
      version: ${{ needs.server_cd.outputs.releaseVersion }}
      dockerPlatforms: linux/amd64,linux/arm64
    secrets:
      dockerHubUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKER_TOKEN }}

  bridge_ci:
    name: systemd_status_bridge - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    needs:
      - rpc_package
      - client_package
    with:
      workingDirectory: systemd_status_bridge
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true
      unitTestPaths: ""
  bridge_cd:
    name: systemd_status_bridge - Compile and Release
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    needs:
      - rpc_package
      - client_package
      - bridge_ci
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.bridge_ci.outputs.enabledPlatforms }}
      workingDirectory: systemd_status_bridge
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true
      archivePrefix: systemd-status-systemctl-bridge
      tagPrefix: bridge/v
      releaseRef: refs/heads/server_pod
  bridge_deploy:
    name: systemd_status_bridge - Create debian package
    needs:
      - bridge_cd
    if: needs.bridge_cd.outputs.releaseCreated == 'true'
    uses: Skycoder42/dart_test_tools/.github/workflows/deb.yml@main
    with:
      workingDirectory: systemd_status_bridge
      packagecloudRepository: systemd_status/ubuntu/jammy
    secrets:
      packagecloudToken: ${{ secrets.PACKAGECLOUD_TOKEN }}

  flutter_ci:
    name: systemd_status_flutter - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    needs:
      - rpc_package
      - client_package
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true
      unitTestPaths: ""
  # flutter_cd:
  #   name: systemd_status_flutter - CD
  #   uses: Skycoder42/dart_test_tools/.github/workflows/deploy.yml@main
  #   needs:
  #     - rpc_package
  #     - client_package
  #     - flutter_ci
  #   with:
  #     enabledPlatforms: ${{ needs.flutter_ci.outputs.enabledPlatforms }}
  #     workingDirectory: systemd_status_flutter
  #     artifactDependencies: >-
  #       systemd_status_rpc
  #       systemd_status_client
  #     tagPrefix: flutter/v
  #     googlePlayTrack: internal
  #     googlePlayReleaseStatus: draft
  #   secrets:
  #     keystore: ${{ secrets.UPLOAD_KEYSTORE }}
  #     keystorePassword: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
  #     googlePlayKey: ${{ secrets.GOOGLE_PLAY_KEY }}
  flutter_build_linux:
    name: systemd_status_flutter - Build flatpak bundle
    needs:
      - rpc_package
      - client_package
      - flutter_ci
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

        include:
          - arch: aarch64
            qemuArch: arm64
    steps:
      - name: Install docker # Docker is required by the docker/setup-qemu-action which enables emulation
        if: ${{ matrix.qemuArch }}
        run: dnf -y install docker
      - name: Setup QEMU
        if: ${{ matrix.qemuArch }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.qemuArch }}
      - name: Import GPG public key
        run: echo '${{ env.FLUTTER_SDK_GPG_KEY }}' | gpg --import
      - name: Download flatpak flutter SDK
        run: >-
          curl --fail-with-body -L
          -o '/tmp/flutter.flatpak'
          'https://github.com/Skycoder42/dart_test_tools/releases/download/flatpak-flutter-extension%2F${{ env.SDK_VERSION }}/org.freedesktop.Sdk.Extension.flutter_${{ env.SDK_VERSION }}_${{ matrix.arch }}.flatpak'
      - name: Install flatpak flutter SDK
        run: flatpak install --system -y --noninteractive '/tmp/flutter.flatpak'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          path: ${{ github.workspace }}/.artifacts
      - name: Build flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: de.skycoder42.systemdStatusFlutter.flatpak
          manifest-path: systemd_status_flutter/linux/flatpak/de.skycoder42.systemdStatusFlutter.yaml
          verbose: true
          cache: false
          arch: ${{ matrix.arch }}
