on:
  workflow_call:
    outputs:
      releaseVersion:
        value: ${{ jobs.flutter_deploy.outputs.releaseVersion }}

jobs:
  flutter_ci:
    name: systemd_status_flutter - CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true
      unitTestPaths: ""

  flutter_build_linux:
    name: systemd_status_flutter - Build flatpak bundles
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-linux.yml@main
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      manifestPath: linux/flatpak/de.skycoder42.systemdStatusFlutter.yaml
      bundleName: de.skycoder42.systemdStatusFlutter.flatpak
    secrets:
      gpgKeyId: ${{ secrets.GPG_KEY_ID }}
      gpgKey: ${{ secrets.GPG_KEY }}

  flutter_build_windows:
    name: systemd_status_flutter - Build msix installer
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-windows.yml@main
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true

  flutter_build_macos:
    name: systemd_status_flutter - Build DMG image installer
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-macos.yml@main
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true
      dmgConfigPath: macos/dmg-config.json

  flutter_build_web:
    name: systemd_status_flutter - Build web archive
    needs:
      - flutter_ci
    uses: Skycoder42/dart_test_tools/.github/workflows/build-web.yml@main
    with:
      workingDirectory: systemd_status_flutter
      artifactDependencies: >-
        systemd_status_rpc
        systemd_status_client
      buildRunner: true

  flutter_deploy:
    name: systemd_status_flutter - Deploy apps
    uses: Skycoder42/dart_test_tools/.github/workflows/deploy.yml@main
    needs:
      - flutter_ci
      - flutter_build_linux
      - flutter_build_windows
      - flutter_build_macos
      - flutter_build_web
    permissions:
      contents: write
    with:
      enabledPlatforms: ${{ needs.flutter_ci.outputs.enabledPlatforms }}
      workingDirectory: systemd_status_flutter
      tagPrefix: app/v
      targetRepo: Skycoder42/homebrew-systemd_status
    secrets:
      gpgKeyId: ${{ secrets.GPG_KEY_ID }}
      gpgKey: ${{ secrets.GPG_KEY }}
      targetRepoToken: ${{ secrets.HOMEBREW_REPO_PAT }}
