on:
  workflow_call:
    inputs:
      releaseCreated:
        type: string
        required: true
      releaseVersion:
        type: string
        required: true
      appVersion:
        type: string
        required: true

jobs:
  server_deploy:
    name: systemd_status_server - Publish docker image
    uses: Skycoder42/dart_test_tools/.github/workflows/docker.yml@main
    if: inputs.releaseCreated == 'true'
    with:
      imageName: skycoder42/systemd-status-server
      version: ${{ inputs.releaseVersion }}
      dockerPlatforms: linux/amd64,linux/arm64
      dockerBuildArgs: |
        APP_VERSION=${{ inputs.appVersion }}
    secrets:
      dockerHubUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKER_TOKEN }}
